# ssh-keygen -t rsa -b 4096 -N "" -f travis_key
# travis login --org --github-token XXXXXX
# travis encrypt-file travis_key (skip --add since it modifies .travis.yml in weird ways)
# travis encrypt-file travis_key.pub

os: osx # linux
# dist: trusty
# sudo: required

language: cpp
compiler: gcc

env:
  global:
  - secure: "KdXiswIO6XXsRAQS3uPwvFORLM7m7WIV9+e2nV6DmbO749LqX0npOhohiY6K3JFjCi0bEM3Tby2SUj+47a5jZJKvoeDMjEO1viBOoBFw/RmoL0WtH6bhimiWxFLFkG5MnsYZA/o472OevEsfc2xoq+ronp0dIkYjFiNPXtxursrX2DcEIwuamh16V3ISjuyN9EoJbChf2htG10cf63FGazPC2jJMNG25w2H1/ZNpQVLvclzB33tIivaFEonk7dSS0Vnmbv+uMhHXwzaM22gm8KYQdPo+jV5H2GNuuO4WttwSusq/hUCCh9HYmrjO+5prpQTVEjRtqkX8aiqgCA7GQac1RtcIRkelm2yHP87hK8B0qvculdq8w1fNF7G5cmzai+i61GhwLm/Zgae8jQs97WBfoKmKNr3K7KzT6QsjMV2NOrv6H7zV2eJSOg/nFA55mipq2RMKEzCiMoYawyaV3p0W/jVQ+8D/SgbgOrGeTzHgosrwDtIbQQDTcHss2Pxn3OccVosCIW+atkEc9OHrO4CM2HLqfBVQvRcTpZgjmZUGx7BwoyOfZTD9uz6yBk4AjXXyFZF0H829ZOld1JhXGwx6vrJ/xjP1pcdyYsc49IPE7SuJC0JWY+kJeftjwtnwcYWGudLeBbFSKnfnZOZTaYX6xsGTc/SZJxp/qfqcaTk="

script:
# As of 2017-12-23, osx is 10.12 by default, 
# cf. https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
# Configure SSH keys
- openssl aes-256-cbc -K $encrypted_d7f434807f41_key -iv $encrypted_d7f434807f41_iv -in travis_key.enc -out travis_key -d
- openssl aes-256-cbc -K $encrypted_d7f434807f41_key -iv $encrypted_d7f434807f41_iv -in travis_key.pub.enc -out travis_key.pub -d
- cat travis_key.pub >> ~/.ssh/authorized_keys
- chmod 600 travis_key
- ls -laR
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo dscl . -passwd /Users/travis ${SSH_PASSWORD}; else echo travis:${SSH_PASSWORD} | sudo chpasswd ; fi
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo systemsetup -setremotelogin on; fi
# - sudo sed -e 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/' -i .bak /etc/ssh/sshd_config
# - sudo sed -e 's/PasswordAuthentication no/PasswordAuthentication yes/' -i .bak /etc/ssh/sshd_config
# - sudo sed -e 's/PubkeyAuthentication yes/PubkeyAuthentication no/' -i .bak /etc/ssh/sshd_config
# - cat /etc/ssh/sshd_config
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo launchctl stop com.openssh.sshd ; sleep 10; sudo launchctl start com.openssh.ssh ; else sudo service ssh restart; fi
# - curl -O -L http://downloads.sourceforge.net/project/sshpass/sshpass/1.05/sshpass-1.05.tar.gz
# - tar xf sshpass-1.05.tar.gz
# - cd sshpass-1.05
# - ./configure
# - make
# - ./sshpass -p ${SSH_PASSWORD} ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no travisci@${BOUNCE_HOST}
# Open SSH tunnel
# - ssh -R 9999:localhost:22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=yes -i travis_key travisci@${BOUNCE_HOST}

# ssh -p 9999 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o PubkeyAuthentication=no travis@localhost
