language: cpp
python:
  - "2.7"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python; fi
  #- pip install --user nose
  #- ls -aR ${HOME}/.local
script:
  - echo ${TRAVIS_OS_NAME}
  - echo ${PATH}
  - find /usr /opt -name "libpython2.7.so" || true
  - export PATH=/foo/bar:${PATH}
after_success:
  - echo ${PATH}
  - which nosetests-2.7
