language: cpp
#python:
#  - "2.7"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
before_install:
  #- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python; brew link --overwrite python; fi
  - pip install --user nose
  #- ls -aR ${HOME}/.local
  - export PATH=$(python -c 'import site; print(site.getuserbase())')/bin:${PATH}
script:
  #- echo ${TRAVIS_OS_NAME}
  #- echo ${PATH}
  - find /usr /opt -name "libpython?.?*" || true
  - cmake .
after_success:
  - echo ${PATH}
  #- find /usr /opt ${HOME} -name "nosetests*" || true
  - which nosetests-2.7
  #- which nosetests
