language: cpp
python:
  - "2.7"
matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang
before_install:
  - pip install --user nose
  - ls -aR
script:
  - echo ${TRAVIS_OS_NAME}
  - echo ${PATH}
  - find /usr /opt -name "libpython2.7.so"
