language: minimal
sudo: required
services:
  - docker
matrix:
  include:
    - name: "Debian Stretch, Python 2"
      env: { distribution: debian, version: stretch }
    - name: "Debian Jessie, Python 2"
      env: { distribution: debian, version: jessie }
before_install:
  - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ${distribution}_${version} --rm ${distribution}:${version}
install:
  - docker exec ${distribution}_${version} cat /etc/debian_version
script:
  - docker exec ${distribution}_${version} ls ${TRAVIS_BUILD_DIR}
after_success:
  - docker kill ${distribution}_${version}
